"""add_reportes_tareas_y_eventos

Revision ID: 6d3912c035ba
Revises: dbf6b8c313e5
Create Date: 2026-04-30 10:31:19.087646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3912c035ba'
down_revision: Union[str, Sequence[str], None] = 'dbf6b8c313e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha_creada', sa.DateTime(), nullable=False),
    sa.Column('fecha_asignada', sa.DateTime(), nullable=True),
    sa.Column('fecha_iniciada', sa.DateTime(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_estado'), 'tareas', ['estado'], unique=False)
    op.create_index(op.f('ix_tareas_id_servicio'), 'tareas', ['id_servicio'], unique=False)
    op.create_index(op.f('ix_tareas_supervisor_id'), 'tareas', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_tareas_tecnico_id'), 'tareas', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_tareas_tipo'), 'tareas', ['tipo'], unique=False)
    op.create_table('tarea_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.String(length=1000), nullable=True),
    sa.Column('lat_evento', sa.Float(), nullable=True),
    sa.Column('lng_evento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarea_eventos_tarea_id'), 'tarea_eventos', ['tarea_id'], unique=False)
    op.create_index(op.f('ix_tarea_eventos_timestamp'), 'tarea_eventos', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarea_eventos_timestamp'), table_name='tarea_eventos')
    op.drop_index(op.f('ix_tarea_eventos_tarea_id'), table_name='tarea_eventos')
    op.drop_table('tarea_eventos')
    op.drop_index(op.f('ix_tareas_tipo'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_tecnico_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_supervisor_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_id_servicio'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_estado'), table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
