"""add_tarea_fotos

Revision ID: a379f0f58efc
Revises: 6d3912c035ba
Create Date: 2026-05-01 14:47:50.405426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a379f0f58efc'
down_revision: Union[str, Sequence[str], None] = '6d3912c035ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea_fotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('subido_por_nombre', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarea_fotos_tarea_id'), 'tarea_fotos', ['tarea_id'], unique=False)
    op.create_index(op.f('ix_tarea_fotos_timestamp'), 'tarea_fotos', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarea_fotos_timestamp'), table_name='tarea_fotos')
    op.drop_index(op.f('ix_tarea_fotos_tarea_id'), table_name='tarea_fotos')
    op.drop_table('tarea_fotos')
    # ### end Alembic commands ###
