from enum import Enum


class TipoEvento(str, Enum):
    TAREA_CREADA       = "TAREA_CREADA"
    TAREA_ASIGNADA     = "TAREA_ASIGNADA"
    TAREA_TRANSICION   = "TAREA_TRANSICION"
    TAREA_COMPLETADA   = "TAREA_COMPLETADA"
    TAREA_CANCELADA    = "TAREA_CANCELADA"
    PAGO_REGISTRADO    = "PAGO_REGISTRADO"
    PAGO_VERIFICADO    = "PAGO_VERIFICADO"
    SERVICIO_SUSPENDIDO  = "SERVICIO_SUSPENDIDO"
    SERVICIO_REACTIVADO  = "SERVICIO_REACTIVADO"
